### ISSUE TITLE
Does not appear to work

### ISSUE THREAD

**Issue by lividhen** [mistrmochov/magiskWaydroid#2]
I don't seem to be able to get it to work. I previously used [this script](https://github.com/casualsnek/waydroid_script) to no avail but undid the magisk changes it made. Is it supposed to install the app? Installing magisk 26.3 manually only gives me the option to patch a file.

https://github.com/mistrmochov/magiskWaydroid/assets/42221797/53d8310b-3a48-4e76-baf2-77ec3aa23f88

**Comment by mistrmochov** [comment]
Yes, that means It didnt install. What linux distribution do you use? Also keep in mind, that this script is very incomplete, because these magisk files in my script, are generated for my system configuration. Its from the time, when this script: https://github.com/nitanmarcel/waydroid-magisk, was working. So on some systems, It will not work, but I will try to make better script.

**Comment by lividhen** [comment]
I'm on arch Linux.

**Comment by mistrmochov** [comment]
Okay and do you have linux-xanmod-anbox kernel?? If you don't have this specific kernel, magisk just simply will not work, not just with this script

**Comment by lividhen** [comment]
Oh cool! I will try that. I am on linux-zen kernel currently.

**Comment by mistrmochov** [comment]
Yes, with archlinux, unfortunately magisk works only with this specific kernel.
